# Generated by Django 5.0.2 on 2024-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(default='qwe', max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
