# Generated by Django 5.0.2 on 2024-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_customer_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128, verbose_name='Product')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('product_description', models.CharField(default='', max_length=1024, verbose_name='Product description')),
                ('image', models.ImageField(blank=True, default='https://via.placeholder.com/150', null=True, upload_to='static/img/', verbose_name='Image')),
                ('category', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('parrot', 'Parrot')], max_length=50, verbose_name='Category')),
            ],
        ),
    ]
