# Generated by Django 5.0.2 on 2024-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='age',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='goods',
            name='features',
            field=models.CharField(default='', max_length=1024, verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='goods',
            name='producer',
            field=models.CharField(default='', max_length=128, verbose_name='Producer'),
        ),
        migrations.AddField(
            model_name='goods',
            name='product_class',
            field=models.CharField(default='', max_length=128, verbose_name='Product class'),
        ),
        migrations.AddField(
            model_name='goods',
            name='taste',
            field=models.CharField(default='', max_length=128, verbose_name='Taste'),
        ),
    ]
