# Generated by Django 5.0.2 on 2024-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_goods_age_goods_features_goods_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='age',
            field=models.CharField(default='', max_length=128, verbose_name='Age'),
        ),
    ]
