# Generated by Django 5.0.2 on 2024-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_basket_basketitem_basket_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_session',
            field=models.CharField(default='', max_length=128, verbose_name='Basket session'),
        ),
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(default='CREATED', max_length=128, verbose_name='Basket session'),
        ),
    ]
