# Generated by Django 5.0.2 on 2024-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_basket_basket_session_basket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='quantity',
            field=models.IntegerField(default=5, verbose_name='Quantity'),
        ),
    ]
