# Generated by Django 5.0.2 on 2024-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_goods_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_cvv',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Card cvv'),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_date',
            field=models.CharField(default=None, max_length=7, null=True, verbose_name='Card date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Card number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=128, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.CharField(default='', max_length=128, verbose_name='House'),
        ),
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.CharField(default='', max_length=128, verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', max_length=128, verbose_name='Street'),
        ),
    ]
