# Generated by Django 5.0.2 on 2024-02-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_customer_card_cvv_customer_card_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Order Date and Time')),
                ('confirmation_code', models.CharField(max_length=128, verbose_name='Confirmation Code')),
                ('confirmation_status', models.BooleanField(default=False, verbose_name='Confirmation Status')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.basket')),
            ],
        ),
    ]
